
import { Card, CardContent } from "@/components/ui/card";
import { formatNumber } from "@/utils/formatNumber";
import { Invoice } from "@/redux/slices/invoiceSlice";

interface InvoicePreviewProps {
  invoice: Invoice;
}

const InvoicePreview = ({ invoice }: InvoicePreviewProps) => {
  return (
    <Card className="w-full">
      <CardContent className="p-8">
        <div className="flex flex-col gap-6">
          {/* Header */}
          <div className="text-center">
            <h1 className="text-2xl font-bold">Sharda Mandap Service</h1>
            <p className="text-gray-600">
              Porbandar Baypass, Jalaram Nagar, Mangrol, Dist. Junagadh - 362225
            </p>
            <p className="text-gray-600">
              GST NO: 24AOSPP7196L1ZX | Mobile: 98246 86047
            </p>
          </div>

          <hr className="border-gray-200" />

          {/* Quotation Info */}
          <div>
            <h2 className="text-xl font-bold mb-2">Quotation</h2>
            <div className="grid grid-cols-2">
              <p><span className="font-medium">Invoice No:</span> {invoice.invoiceNumber}</p>
              <p><span className="font-medium">Party Name:</span> {invoice.partyName}</p>
              <p><span className="font-medium">Date:</span> {invoice.date}</p>
            </div>
          </div>

          <hr className="border-gray-200" />

          {/* Billing Details */}
          <div>
            <h2 className="text-xl font-bold mb-2">Billing Details</h2>
            <div className="overflow-x-auto">
              <table className="invoice-table">
                <thead>
                  <tr>
                    <th>Sr No</th>
                    <th>Description</th>
                    <th>Quantity</th>
                    <th>Rate (₹)</th>
                    <th>Total (₹)</th>
                  </tr>
                </thead>
                <tbody>
                  {invoice.items.map((item, index) => (
                    <tr key={item.id}>
                      <td>{index + 1}</td>
                      <td>{item.description}</td>
                      <td>{item.quantity}</td>
                      <td>{formatNumber(item.rate)}</td>
                      <td>{formatNumber(item.total)}</td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>
          </div>

          <hr className="border-gray-200" />

          {/* Summary */}
          <div>
            <h2 className="text-xl font-bold mb-2">Summary</h2>
            <div className="flex flex-col items-end">
              <div className="w-full max-w-xs">
                <div className="flex justify-between">
                  <span>Total without GST:</span>
                  <span>₹ {formatNumber(invoice.subtotal)}</span>
                </div>
                <div className="flex justify-between">
                  <span>GST (18%):</span>
                  <span>₹ {formatNumber(invoice.gst)}</span>
                </div>
                <div className="flex justify-between font-bold border-t border-gray-200 pt-2 mt-2">
                  <span>Amount with GST:</span>
                  <span>₹ {formatNumber(invoice.total)}</span>
                </div>
              </div>
            </div>
          </div>

          <hr className="border-gray-200" />

          {/* Footer */}
          <div className="text-center text-gray-600">
            <p className="font-medium">Generated by Sharda Mandap Service</p>
            <p>Contact: 98246 86047</p>
          </div>
        </div>
      </CardContent>
    </Card>
  );
};

export default InvoicePreview;
