
import { BlockNoteEditor, PartialBlock } from "@blocknote/core";
import { BlockNoteView, useBlockNote } from "@blocknote/react";
import "@blocknote/core/style.css";
import { useEffect } from "react";
import { Switch } from "@/components/ui/switch"
import { Label } from "@/components/ui/label"

interface InvoiceEditorProps {
  onSave?: (markdown: string) => void;
  initialContent?: string;
}

const InvoiceEditor = ({ onSave, initialContent }: InvoiceEditorProps) => {
  const editor: BlockNoteEditor = useBlockNote({
    initialContent: [
      {
        type: "heading-1",
        content: "Quotation"
      },
      {
        type: "paragraph",
        content: "Sharda Mandap Service"
      },
      {
        type: "paragraph",
        content: "Porbandar Baypass, Jalaram Nagar, Mangrol, Dist. Junagadh - 362225"
      },
      {
        type: "paragraph",
        content: "GST NO: 24AOSPP7196L1ZX | Mobile: 98246 86047"
      },
      {
        type: "divider",
      },
      {
        type: "heading-2",
        content: "Invoice Details"
      },
      {
        type: "paragraph",
        content: "Invoice No: [To be filled]"
      },
      {
        type: "paragraph",
        content: "Party Name: Gulab Oil"
      },
      {
        type: "paragraph",
        content: "Date: 23-04-2025"
      },
      {
        type: "divider",
      },
      {
        type: "table",
        content: [
          ["Sr No", "Description (વર્ણન)", "Quantity (જથ્થો)", "Rate (₹)", "Total (₹)"],
          ["1", "મેન ગેટ", "2", "7,000", "14,000"],
          ["2", "Dom (sft)", "4,950", "33.33", "1,65,000"],
          // ... Add all other rows
        ]
      },
      {
        type: "divider",
      },
      {
        type: "heading-2",
        content: "Summary"
      },
      {
        type: "table",
        content: [
          ["Description", "Amount (₹)"],
          ["Total without GST", "4,03,000"],
          ["GST (18%)", "72,540"],
          ["Amount with GST", "4,75,540"]
        ]
      },
      {
        type: "divider",
      },
      {
        type: "paragraph",
        content: "Generated by Sharda Mandap Service"
      },
      {
        type: "paragraph",
        content: "For inquiries, contact us at 98246 86047"
      }
    ]
  });

  const [showGst, setShowGst] = useState(true);

  const updateGstCalculation = () => {
    const blocks = editor.getBlocks();
    const summaryTableIndex = blocks.findIndex(block => 
      block.type === "table" && 
      block.content?.[0]?.[0] === "Description"
    );

    if (summaryTableIndex !== -1) {
      const totalWithoutGst = 403000; // This should be calculated from items
      const gstAmount = showGst ? totalWithoutGst * 0.18 : 0;
      const totalWithGst = totalWithoutGst + gstAmount;

      editor.updateBlock(blocks[summaryTableIndex], {
        type: "table",
        content: [
          ["Description", "Amount (₹)"],
          ["Total without GST", totalWithoutGst.toLocaleString('en-IN')],
          ...(showGst ? [["GST (18%)", gstAmount.toLocaleString('en-IN')]] : []),
          [`${showGst ? "Amount with GST" : "Total Amount"}`, totalWithGst.toLocaleString('en-IN')]
        ]
      });
    }
  };

  useEffect(() => {
    updateGstCalculation();
  }, [showGst]);

  return (
    <div className="space-y-4">
      <div className="flex items-center space-x-2">
        <Switch
          id="gst-switch"
          checked={showGst}
          onCheckedChange={setShowGst}
        />
        <Label htmlFor="gst-switch">Apply GST (18%)</Label>
      </div>
      
      <div className="border rounded-lg overflow-hidden">
        <BlockNoteView
          editor={editor}
          theme="light"
        />
      </div>
    </div>
  );
};

export default InvoiceEditor;
