// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lqknmwiqiajspfopxsfu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imxxa25td2lxaWFqc3Bmb3B4c2Z1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU4NDA0ODcsImV4cCI6MjA2MTQxNjQ4N30.O1TLuKGPlBqwQ_H-VYtAywQ_yKmmQRs-Y15ONkrUkro";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);